project_id = "pxoidghxgtlcqbnsnmvl"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.shiprocket-create-shipment]
verify_jwt = true
