project_id = "pxoidghxgtlcqbnsnmvl"

[functions.create-razorpay-order]
verify_jwt = false

[functions.verify-razorpay-payment]
verify_jwt = false

[functions.shiprocket-create-shipment]
verify_jwt = false

[functions.validate-coupon]
verify_jwt = false

[functions.create-upgrade-order]
verify_jwt = false

[functions.verify-upgrade-payment]
verify_jwt = false

[functions.verify-domain-dns]
verify_jwt = false

[functions.delivery-boy-auth]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.shiprocket-webhook]
verify_jwt = false

[functions.log-error]
verify_jwt = false

[functions.log-performance]
verify_jwt = false

[functions.admin-otp]
verify_jwt = false

[functions.store-customer-otp]
verify_jwt = false
